easy_admin:
    user:
      name_property_path: 'originUsername'
    site_name: 'Senses of Cuba <em style="font-size: 80%;">Management</em>'
    list:
      # hide actions by default in a dropdown menu...
#      collapse_actions: true
      actions: ['show', 'edit', 'delete']
    design:
        assets:
          css:
            - '/admin/css/rewrite.css'
        brand_color: '#fdc416'
        menu:
          - { entity: 'Categories', label: 'Kind of products' }
          - Products
          - { entity: 'Documents', label: 'Documents About Cuba' }
          - Users
        #form_theme: ['@FOSCKEditor/Form/ckeditor_widget.html.twig']
        form_theme:
          - '@EasyAdmin/form/bootstrap_4.html.twig'
          - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    entities:

      Categories:
        class: App\Entity\ProductCategory
        form:
          fields:
            - { property: 'title' }
            #            - { property: 'ChildNodeOf', type: 'entity', type_options: { class:  'App\Entity\ProductCategory' } }
            - { property: 'image', type: 'file' }
            - { property: 'parent' }
        show:
          fields:
            - { property: 'title' }
            - { property: 'getImageWebPath', type: 'file', template: 'admin/partial/image.html.twig', label: 'Image' }
            - { property: 'parent' }
        list:
          fields:
            - { property: 'title' }
            - { property: 'getImageWebPath', type: 'file', template: 'admin/partial/image.html.twig',label: 'Image' }
            - { property: 'parent' }

      Products:
        class: App\Entity\Product
        list:
          fields:
            - { property: 'id' }
            - { property: 'title' }
            - { property: 'getImageWebPath', type: 'file', template: 'admin/partial/image.html.twig',label: 'Image' }
            - { property: 'getFileWebPath',  type: 'file', template: 'admin/partial/file.html.twig' , label: 'PDF'}
            - { property: 'category' }
        # ...
        show:
          fields:
            - { property: 'title' }
            - { property: 'getImageWebPath', type: 'file', template: 'admin/partial/image.html.twig', label: 'Image' }
            - { property: 'getFileWebPath',  type: 'file', template: 'admin/partial/file.html.twig' , label: 'PDF'}
            - { property: 'category' }
        form:
          fields:
            - { property: 'title' }
            - { property: 'file', type: 'file' }
            - { property: 'image', type: 'file' }
            - { property: 'category' }

      Documents:
        class: App\Entity\Document
        list:
          fields:
            - { property: 'id' }
            - { property: 'title' }
            - { property: 'getImageWebPath', type: 'file', template: 'admin/partial/image.html.twig',label: 'Image' }
            - { property: 'getFileWebPath',  type: 'file', template: 'admin/partial/file.html.twig' , label: 'PDF'}

        # ...
        show:
          fields:
            - { property: 'title' }
            - { property: 'getImageWebPath', type: 'file', template: 'admin/partial/image.html.twig', label: 'Image' }
            - { property: 'getFileWebPath',  type: 'file', template: 'admin/partial/file.html.twig' , label: 'PDF'}

        form:
          fields:
            - { property: 'title' }
            - { property: 'file', type: 'file' }
            - { property: 'image', type: 'file' }


      Users:
        class: App\Entity\User
        show:
          fields:
            - { property: 'id' }
            - { property: 'enabled' }
            - { property: 'email' }
            - { property: 'name' }
#            - { property: 'lastName' }
            - { property: 'enterprise' }
            - { property: 'travelAgency' }
            - { property: 'country' }
            - { property: 'web' }
            - { property: 'getAllRolesAsString', type: 'array' }
        form:
          fields:
            - { property: 'enabled' }
            - { property: 'name' }
#            - { property: 'lastName' }
            - { property: 'enterprise' }
            - { property: 'travelAgency' }
            - { property: 'country' }
            - { property: 'web' }
            - { property: 'userRoles', type: 'choice', type_options: {choices: {ADMIN: 'ADMIN', USER: 'USER'}}}
        list:
          fields:
            - { property: 'enabled' }
            - { property: 'name' }
#            - { property: 'lastName' }
            - { property: 'enterprise' }
            - { property: 'travelAgency' }
            - { property: 'Admin', type: 'boolean' }
#            - { property: 'web' }
#      UserRoles:
#        class: App\Entity\UserRole
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
